StEP/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('admin_management.urls', namespace="admin_management")),
    url(r'^', include('user_management.urls', namespace="user_management")),
]

user_management/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from user_management.views import *

urlpatterns = [
    url(r'modify$', modify_profile, name='modify'),
    url(r'change_password', change_password, name='change_password'),
    url(r'^login$', auth_views.login, {'template_name': 'user_management/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^registration/$', student_register, name="student_registration"),
    url(r'^teacher_adding/$', teacher_adding, name="teacher_adding"),
    url(r'^company_registration/$', company_register, name="company_registration"),
    url(r'^profile/', profile, name="profile"),
]

user_management/models.py
from django.db import models
from django.contrib.auth.models import User


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    is_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class SimpleUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    second_name = models.CharField(max_length=40)
    third_name = models.CharField(max_length=40)
    banned = models.BooleanField(default=False)
    def create_user(self, first_name, second_name, third_name, email, password):
        user = User(first_name=first_name, username=email, password=password)
        user.save()
        user = SimpleUser(user=user, second_name=second_name, third_name=third_name)
        user.save()
        return user
    def get_first_name(self):
        return self.user.first_name
    def get_second_name(self):
        return self.second_name
    def get_third_name(self):
        return self.third_name
    def get_email(self):
        return self.user.username
    def get_password(self):
        return self.user.password
    def set_first_name(self, first_name):
        self.user.first_name = first_name
        self.user.save()
        self.save()
    def set_second_name(self, second_name):
        self.second_name = second_name
        self.save()
    def set_third_name(self, third_name):
        self.third_name = third_name
        self.save()
    def set_email(self, email):
        self.user.username = email
        self.user.save()
        self.save()
    def set_password(self, password):
        self.user.set_password(password)
        self.user.save()
        self.save()

    def __str__(self):
        return self.user.username + ', ' + \
               ' '.join([self.user.first_name, self.second_name, self.third_name])

    def is_teacher(self):
        return hasattr(self, 'teacher')

    def is_student(self):
        return not self.is_teacher()


class Teacher(models.Model):
    user = models.OneToOneField(SimpleUser, on_delete=models.CASCADE)
    description = models.TextField(max_length=500)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.use

class Admin(models.Model):
    user = models.ForeignKey(SimpleUser)

user_management/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages

from user_management.helpers import validator
from user_management.models import *
from user_management.models import SimpleUser


# Create your views here.

@login_required
def modify_profile(request):
    if request.method == 'GET':
        user = SimpleUser.objects.get(user=request.user)
        first_name = user.get_first_name()
        second_name = user.get_second_name()
        third_name = user.get_third_name()
        email = user.get_email()
        return render(request, 'user_management/modify_profile.html', {'first_name': first_name,
                                                                       'second_name': second_name,
                                                                       'third_name': third_name,
                                                                       'email': email})
    if request.method == 'POST':
        first_name = request.POST['first_name']
        second_name = request.POST['second_name']
        third_name = request.POST['third_name']
        email = request.POST['email']
        errors = ''
        if not validator.is_fields_filled(first_name, second_name, third_name, email):
            errors = 'Fill all fields'
        elif not validator.is_correct_email(email):
            errors = 'Incorrect email'
        elif not validator.is_correct_name(first_name):
            errors = 'Incorrect name'
        elif not validator.is_correct_name(second_name):
            errors = 'Incorrect second name'
        elif not validator.is_correct_name(third_name):
            errors = 'Incorrect third name'
        elif not email == request.user.username and not validator.is_email_free(email):
            errors = 'Email is already taken'
        else:
            user = SimpleUser.objects.get(user=request.user)
            user.set_first_name(first_name)
            user.set_second_name(second_name)
            user.set_third_name(third_name)
            user.set_email(email)
        messages.add_message(request, messages.INFO, errors)
        return HttpResponseRedirect(reverse('user_management:modify'))
    else:
        return HttpResponse('Not supported')


@login_required
def change_password(request):
    if request.method != 'POST':
        return HttpResponse('Not supported')
    else:
        errors = ''
        user = SimpleUser.objects.get(user=request.user)
        if not check_password(request.POST['old_password'], user.get_password()):
            errors = 'Wrong old password'
        elif request.POST['new_password'] == '' or request.POST['repeated_password'] == '':
            errors = 'Fill all fields'
        elif request.POST['new_password'] != request.POST['repeated_password']:
            errors = 'Wrong repeated password'
        elif not validator.is_correct_password(request.POST['new_password']):
            errors = 'Пароль должен содержать от шести до тридцати симовлов, может содержать буквы латиницы, цифры, -, _'
        else:
            user.set_password(request.POST['new_password'])
        messages.add_message(request, messages.INFO, errors)
        user = authenticate(username= user.get_email(), password=request.POST['new_password'])
        auth_login(request, user)
        return HttpResponseRedirect(reverse('user_management:modify'))

def student_register(request):
    if request.method == "POST":
        result = simple_user_registration(request)
        if isinstance(result, SimpleUser):
            return HttpResponseRedirect(reverse('user_management:login'))
        else:
            return render(request, "user_management/registration.html", result)

    else:
        return render(request, "user_management/registration.html")


def company_register(request):
    if request.method == "POST":
        email = request.POST['email']
        company_name = request.POST['company_name']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        args = {'email': email, 'company_name': company_name}

        if not validator.is_fields_filled(email, company_name, password, confirm_password):
            args['error'] = 'Please fill in all fields'
        elif not validator.is_correct_email(email):
            args['error'] = 'Invalid mail format'
        elif not validator.is_email_free(email):
            args['error'] = 'User with this mail already exists'
        elif not validator.is_correct_password(password):
            args['error'] = 'Invalid password format'
        elif not validator.is_passwords_match(password, confirm_password):
            args['error'] = 'Passwords don\'t match'

        if args.get('error'):
            return render(request, "user_management/company_registration.html", args)

        user = User(username=email,
                    password=make_password(password, salt=None, hasher='default'))
        user.save()

        company = Company(user=user, name=company_name)
        company.save()
        return HttpResponse("Your application for registration has been sent to the administrator for confirmation")

    else:
        return render(request, "user_management/company_registration.html")


@login_required
def teacher_adding(request):
    user = request.user
    if not hasattr(user, 'company') or not user.company.is_confirmed:
        raise Http404

    if request.method == "POST":
        description = request.POST['description']

        result = simple_user_registration(request)
        if isinstance(result, SimpleUser):
            teacher = Teacher(user=result, description=description, company=request.user.company)
            teacher.save()
            return HttpResponse('The teacher is registered. Here will be move to the list of teachers page')
        else:
            result['description'] = description
            return render(request, "user_management/teacher_adding.html", result)

    else:
        return render(request, "user_management/teacher_adding.html")


def simple_user_registration(request):
    email = request.POST['email']
    first_name = request.POST['first-name']
    second_name = request.POST['second-name']
    third_name = request.POST['third-name']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']

    args = {'email': email, 'first_name': first_name, 'second_name': second_name, 'third_name': third_name}

    if not validator.is_fields_filled(email, first_name, second_name, third_name, password, confirm_password):
        args['error'] = 'Please fill in all fields'
    elif not validator.is_correct_email(email):
        args['error'] = 'Invalid mail format'
    elif not validator.is_email_free(email):
        args['error'] = 'User with this mail already exists'
    elif not validator.is_correct_password(password):
        args['error'] = 'Invalid password format'
    elif not validator.is_passwords_match(password, confirm_password):
        args['error'] = 'Passwords don\'t match'
    elif not validator.is_correct_name(first_name, second_name, third_name):
        args['error'] = 'Invalid name format'

    if args.get('error'):
        return args

    user = User(username=email,
                password=make_password(password, salt=None, hasher='default'),
                first_name=first_name)
    user.save()
    simple_user = SimpleUser(user=user, second_name=second_name, third_name=third_name)
    simple_user.save()
    return simple_user


def profile(request):
    return render(request, "user_management/profile.html")

user_management/templates/user_management/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

user_management/templates/user_management/company_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STEP</title>
</head>
<body>
    <h1>It is company registration page</h1>
    <p>Approval of the administrator is required to confirm registration!</p>
    <hr/>
    <form action="" method="post">
        {% csrf_token %}
        <h4>Email: </h4>
        <input type="email" name="email" {% if email %} value="{{ email }}"
                                        {% else %} placeholder="email" {% endif %}/>
        <br/>
        <h4>Company name: </h4>
        <input type="text" name="company_name" {% if company_name %} value="{{ company_name }}"
                                            {% else %} placeholder="company name" {% endif %}/>
        <br/>
        <h4>Password: </h4>
        <input type="password" name="password" placeholder="password"/>
        <br/>
        <input type="password" name="confirm_password" placeholder="confirm password"/>
        <br/><br/>
        <button type="submit">Register your company</button>
    </form>

        {% if error %}
            <hr/>
            <p>{{ error }}</p>
        {% endif %}
</body>
</html>

user_management/templates/user_management/login.html
{% extends 'user_management/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>Hello, {{ user.username }}</h2>
        <a href="{% url 'user_management:logout' %}">
            <button>Log out</button>
        </a>
    {% else %}
        <h2>Login</h2>
            <form method="post" action="{% url 'user_management:login' %}">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    {% endif %}
{% endblock %}

user_management/templates/user_management/modify_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Modify</title>
</head>
<body>
<form action="{% url "user_management:modify" %}" method="post">
    {% csrf_token %}
    <input type="text" name="first_name" value="{{ first_name }}"/>
    <input type="text" name="second_name" value="{{ second_name }}"/>
    <input type="text" name="third_name" value="{{ third_name }}"/>
    <input type="text" name="email" value="{{ email }}"/>
    <input type="submit" value="Modify"/>
</form>

<form action="{% url "user_management:change_password" %}" method="post">
    {% csrf_token %}
    <input type="password" name="old_password"/>
    <input type="password" name="new_password"/>
    <input type="password" name="repeated_password"/>
    <input type="submit" value="Change password"/>
</form>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>

user_management/templates/user_management/profile.html
<h1><b>View Profile</b></h1>
<img src="" width="189" height="255" alt="User Photo" name="user_photo">
<p><label for="user">Имя: </label></p>
<p><label for="second_name">Фамилия: </label></p>
<p><label for="third_name">Отчество: </label></p>
<input type="submit" name="modify_button" value="Modify"/>

user_management/templates/user_management/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STEP</title>
</head>
<body>
    <h1>It is registration page</h1>
    <hr/>
    <form action="" method="post">
        {% csrf_token %}
        <h4>Email: </h4>
        <input type="email" name="email" {% if email %} value="{{ email }}"
                                        {% else %} placeholder="email" {% endif %}/>
        <br/>
        <h4>Full name: </h4>
        <input type="text" name="first-name" {% if first_name %} value="{{ first_name }}"
                                            {% else %} placeholder="first-name" {% endif %}/>
        <input type="text" name="second-name" {% if second_name %} value="{{ second_name }}"
                                            {% else %} placeholder="second-name" {% endif %}/>
        <input type="text" name="third-name" {% if third_name %} value="{{ third_name }}"
                                            {% else %} placeholder="third-name" {% endif %}/>
        <br/>
        <h4>Password: </h4>
        <input type="password" name="password" placeholder="password"/>
        <br/>
        <input type="password" name="confirm_password" placeholder="confirm password"/>
        <br/><br/>
        <button type="submit">Sign Up</button>

        {% if error %}
            <hr/>
            <p>{{ error }}</p>
        {% endif %}
    </form>
</body>
</html>

user_management/templates/user_management/teacher_adding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STEP</title>
</head>
<body>
    <h1>It is teacher adding page</h1>
    <hr/>
    <form action="" method="post">
        {% csrf_token %}
        <h4>Email: </h4>
        <input type="email" name="email" {% if email %} value="{{ email }}"
                                        {% else %} placeholder="email" {% endif %}/>
        <br/>
        <h4>Full name: </h4>
        <input type="text" name="first-name" {% if first_name %} value="{{ first_name }}"
                                            {% else %} placeholder="first-name" {% endif %}/>
        <input type="text" name="second-name" {% if second_name %} value="{{ second_name }}"
                                            {% else %} placeholder="second-name" {% endif %}/>
        <input type="text" name="third-name" {% if third_name %} value="{{ third_name }}"
                                            {% else %} placeholder="third-name" {% endif %}/>
        <br/>
        <h4>Description: </h4>
        <textarea rows="10" cols="45" name="description">{% if description %}{{ description }}{% endif %}</textarea>
        <br/>
        <h4>Password: </h4>
        <input type="password" name="password" placeholder="password"/>
        <br/>
        <input type="password" name="confirm_password" placeholder="confirm password"/>
        <br/><br/>
        <button type="submit">Add teacher</button>

        {% if error %}
            <hr/>
            <p>{{ error }}</p>
        {% endif %}
    </form>
</body>
</html>